# Numpy Arrays in Python

In [46]:
#import library
import numpy as np

In [58]:
lst = [1,2,3,4]
arr = np.array(lst)

In [59]:
arr[3]=5
arr

array([1, 2, 3, 5])

In [60]:
arr[1:3]

array([2, 3])

In [61]:
arr[-1] #last item

5

In [62]:
arr[:-1] #all item except last element

array([1, 2, 3])

In [63]:
arr[::-1] #print array in reverse

array([5, 3, 2, 1])

In [64]:
arr[::-2] #reverse and skip 1 item each time [5, 3(skipped), 2, 1(skipped)]

array([5, 2])

In [66]:
arr[::2]

array([1, 3])

In [67]:
type(arr)

numpy.ndarray

In [68]:
arr.shape

(4,)

In [69]:
lst1=[1,2,3,0]
lst2=[4,5,6,0]
lst3=[7,8,9,0]

arr=np.array([lst1,lst2,lst3])
arr

array([[1, 2, 3, 0],
       [4, 5, 6, 0],
       [7, 8, 9, 0]])

In [70]:
arr.shape

(3, 4)

In [71]:
#indexing
arr[1,2]

6

In [73]:
arr[:,1] #all rows, 2nd column

array([2, 5, 8])

In [74]:
arr[1:, 1:3]

array([[5, 6],
       [8, 9]])

In [76]:
arr[1:,2:]

array([[6, 0],
       [9, 0]])

In [77]:
arr[:,2:4]

array([[3, 0],
       [6, 0],
       [9, 0]])

In [86]:
lst1=[1,2,3,0]
lst2=[4,5,6,0]
lst3=[7,8,9,0]

arr=np.array([lst1,lst2,lst3])

#get Ist and last columns
x = arr[:,0]
y = arr[:,-1]
arr1 = np.array([x,y])
arr1

array([[1, 4, 7],
       [0, 0, 0]])

## EDA - Exploratory Data Analysis - point of view

In [87]:
arr = np.array([1,2,3,4])
arr<2

array([ True, False, False, False])

In [88]:
arr[arr<2]

array([1])

In [89]:
arr

array([1, 2, 3, 4])

In [92]:
lst1=[1,2,3,0]
lst2=[4,5,6,0]
lst3=[7,8,9,0]

arr1=np.array([lst1,lst2,lst3])
arr1

array([[1, 2, 3, 0],
       [4, 5, 6, 0],
       [7, 8, 9, 0]])

In [94]:
arr1.reshape(4,3)

array([[1, 2, 3],
       [0, 4, 5],
       [6, 0, 7],
       [8, 9, 0]])

In [95]:
np.arange(1,10,1) #start, stop-1, step

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [97]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [98]:
np.arange(2,10,2).reshape(2,2)

array([[2, 4],
       [6, 8]])

In [99]:
np.arange(2,10,2).reshape(2,2,1)

array([[[2],
        [4]],

       [[6],
        [8]]])

In [100]:
arr

array([1, 2, 3, 4])

In [101]:
arr * arr

array([ 1,  4,  9, 16])

In [102]:
arr1

array([[1, 2, 3, 0],
       [4, 5, 6, 0],
       [7, 8, 9, 0]])

In [103]:
arr1 * 2

array([[ 2,  4,  6,  0],
       [ 8, 10, 12,  0],
       [14, 16, 18,  0]])

In [104]:
arr1 * arr1

array([[ 1,  4,  9,  0],
       [16, 25, 36,  0],
       [49, 64, 81,  0]])

In [106]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [107]:
np.ones_like((5,3))

array([1, 1])

In [109]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [112]:
np.random.randint(10, 50) #random number from 10 to 49

24

In [118]:
np.random.randint(10, 50, 4) #number of integers

array([20, 14, 18, 25])

In [119]:
np.random.randint(10, 50, 4).reshape(2,2)

array([[15, 10],
       [40, 49]])