# Pandas in Python

In [2]:
import pandas as pd
import numpy as np

In [7]:
arr=np.arange(0, 20).reshape(5,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [10]:
##create dataframe
df = pd.DataFrame(data=arr, 
             index=["Row1", "Row2", "Row3", "Row4", "Row5"],
             columns=["Col1", "Col2", "Col3", "Col4"]
            )
df

Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [11]:
df.head() #show top 5 records

Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [12]:
df.tail() #show last 5 records

Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [16]:
type(df)

pandas.core.frame.DataFrame

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Col1    5 non-null      int32
 1   Col2    5 non-null      int32
 2   Col3    5 non-null      int32
 3   Col4    5 non-null      int32
dtypes: int32(4)
memory usage: 120.0+ bytes


In [18]:
df.describe() #only int type columns selected

Col1       Col2       Col3       Col4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [19]:
df.head()

Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [20]:
df[["Col1", "Col2", "Col3"]]

Col1  Col2  Col3
Row1     0     1     2
Row2     4     5     6
Row3     8     9    10
Row4    12    13    14
Row5    16    17    18

In [26]:
df["Col1"] #by using column name

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: Col1, dtype: int32

In [24]:
type(df["Col1"])

pandas.core.series.Series

In [27]:
type(df[["Col1", "Col2", "Col3"]])

pandas.core.frame.DataFrame

In [29]:
df.loc["Row3"] #using row index name

Col1     8
Col2     9
Col3    10
Col4    11
Name: Row3, dtype: int32

In [30]:
df.loc[["Row3","Row4"]] #using row index name

Col1  Col2  Col3  Col4
Row3     8     9    10    11
Row4    12    13    14    15

In [31]:
df.iloc[2:4,0:2]

Col1  Col2
Row3     8     9
Row4    12    13

In [51]:
df.iloc[:,0:-1]

Col1  Col2  Col3
Row1     0     1     2
Row2     4     5     6
Row3     8     9    10
Row4    12    13    14
Row5    16    17    18

In [41]:
df.iloc[[0,-1]] #Ist and last row

Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row5    16    17    18    19

In [44]:
df.Col1

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: Col1, dtype: int32

In [56]:
df[["Col1", "Col4"]] #print first and last col

Col1  Col4
Row1     0     3
Row2     4     7
Row3     8    11
Row4    12    15
Row5    16    19

In [60]:
df.iloc[:,1:]

Col2  Col3  Col4
Row1     1     2     3
Row2     5     6     7
Row3     9    10    11
Row4    13    14    15
Row5    17    18    19

In [61]:
df.iloc[:,1:].values #convert dataframe to arrays

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

## basic operations

In [62]:
df.isnull().sum() #chk null in columns

Col1    0
Col2    0
Col3    0
Col4    0
dtype: int64

In [63]:
##create dataframe
df1 = pd.DataFrame(data=[[1, np.nan, 3],[4, 5, np.nan]], 
             index=["Row1", "Row2"],
             columns=["Col1", "Col2", "Col3"]
            )
df1

Col1  Col2  Col3
Row1     1   NaN   3.0
Row2     4   5.0   NaN

In [64]:
df1.isnull().sum()

Col1    0
Col2    1
Col3    1
dtype: int64

In [65]:
df1.isnull()

Col1   Col2   Col3
Row1  False   True  False
Row2  False  False   True

In [66]:
df1.isnull().sum()==0

Col1     True
Col2    False
Col3    False
dtype: bool

In [67]:
df1["Col1"].value_counts() #num of times elements present in Col1

1    1
4    1
Name: Col1, dtype: int64

In [68]:
df["Col1"].unique()

array([ 0,  4,  8, 12, 16])

In [70]:
df>2

Col1   Col2   Col3  Col4
Row1  False  False  False  True
Row2   True   True   True  True
Row3   True   True   True  True
Row4   True   True   True  True
Row5   True   True   True  True

In [71]:
df['Col2']>2

Row1    False
Row2     True
Row3     True
Row4     True
Row5     True
Name: Col2, dtype: bool

In [72]:
#Conditional indexing, showing only rows that have > 2 values in col
df[df['Col2']>2]

Col1  Col2  Col3  Col4
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19